### ISSUE TITLE
Open new tab next to the tab where the click happened.

### ISSUE THREAD

**Issue by david-macias** [pyro2927/AWS_SSO_Containers#10]
This is more esthetics any anything else, but I like for my tabs to be grouped together. Root tab (click)->new tab spawn. This extension opens a new tab at the end of all already opened tabs and I would love if that was configurable.

**Comment by pyro2927** [comment]
Fixed in 1.5

**Comment by david-macias** [comment]
Follow up question, how do I upgrade? I figured FF would automatically do it, but I'm still at 1.4.

**Comment by pyro2927** [comment]
It seems like it takes a day or two before it rolls out via update channels. If you remote and then re-add the extension via the FF site it should work. Just tested it on one of my other machines, "check for updates" said that 1.4 was the latest version, but when I removed and reinstalled it 1.5 showed up.
