### ISSUE TITLE
Support signin.aws.amazon.com/saml

### ISSUE THREAD

**Issue by OscarPalafox** [pyro2927/AWS_SSO_Containers#11]
Hi!

Currently, I make use of the page https://signin.aws.amazon.com/saml to select the account and role I am going to access. I'm afraid that the extension is not working for this. Whenever I click sign in, it just enters without a container.
This is how the interface looks:
![aws](https://github.com/pyro2927/AWS_SSO_Containers/assets/46593945/43b5815a-706a-4627-8ddb-fa971a9e103f)

Would be lovely if you could also make this work, let me know if I can provide anything further. Happy to do a PR

**Comment by pyro2927** [comment]
@OscarPalafox do you happen to have any documentation on this login flow? Would be happy to look into it, though I've never used it before so I can make no promises.

**Comment by OscarPalafox** [comment]
Thanks for getting back to me. I land on that page after accessing Okta, I believe there's more info in [this page](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_providers_enable-console-saml.html). Let me know if I can provide more details regarding requests to AWS, or whatever you need 😄.

**Comment by leodag** [comment]
Hi Oscar, I just implemented this on #18, if you can, please try it out!

**Comment by OscarPalafox** [comment]
Hey! I can confirm it works like a charm, thanks so much for looking into it 🙏. You're a legend!!
