### ISSUE TITLE
JUST BROKEN: Method to extract name and role of AWS account to choose correct container is broken just now!

### ISSUE THREAD

**Issue by scastria** [pyro2927/AWS_SSO_Containers#15]
AWS must have just changed the format/content of how they handle SSO connections as your plugin (which I rely on EVERY DAY) now gets confused as to which AWS account is being connected to.  The name of the container chosen is now, the literal string "name" instead of the actual name of the AWS account.  Therefore, no matter which account I click on, I get the same container named "name" as my container.  This, of course, means I cannot open more than 1 AWS account at a time which breaks the point of this plugin.  Please fix right away.  I can donate money if needed.

**Comment by scastria** [comment]
Hmm..  I was just playing with the container name template preference in this plugin which I had customized to just be "name" and deleted it completely.  I then restarted the browser and the default "name role" template was restored AND it did properly name the container.  I then changed the name template back to "name" and restarted my browser and then everything was working again.  Not sure what happened.  Will close this ticket.

**Comment by davidebonavita** [comment]
> AWS must have just changed the format/content of how they handle SSO connections as your plugin (which I rely on EVERY DAY) now gets confused as to which AWS account is being connected to. The name of the container chosen is now, the literal string "name" instead of the actual name of the AWS account. Therefore, no matter which account I click on, I get the same container named "name" as my container. This, of course, means I cannot open more than 1 AWS account at a time which breaks the point of this plugin. Please fix right away. I can donate money if needed.

I have exactly the same issue, check this link:
https://github.com/pyro2927/AWS_SSO_Containers/issues/12#issuecomment-1892022210

I'll try to follow your steps to fix this tomorrow. Thanks bro!

**Comment by jeremyssavage** [comment]
Had the same issue and this fixed it for me too. Just remember to restart your browser after saving the container name template.

Thanks @scastria !

**Comment by davidebonavita** [comment]
Sadly it didn't fix it for me. It still shows `name` and even keeping the default value it shows `name` plus the AWS role. I've restarted Firefox at every step.

![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/11682646/a0ca16b1-8538-4df4-ade2-8eeb596d7df8)

**Comment by jeremyssavage** [comment]
Hm, then I have no idea. It might be worth doing uninstalling and reinstalling the extension, to try and "refresh" the way it is dealing with `name`.

**Comment by cjallen88** [comment]
Should be fixed by #20
