### ISSUE TITLE
Wrong container names & Firefox crashes

### ISSUE THREAD

**Issue by lohrm-stabl** [pyro2927/AWS_SSO_Containers#17]
v1.6
Every account gets opened in the same container with this name:
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/111898561/12c50721-4bc9-457b-9705-d217cfe112aa)

If I close Firefox completely and open containers, Firefox crashes instantly.

**Comment by lohrm-stabl** [comment]
Workaround: change `name` to `number` in the settings:
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/111898561/32aa4108-c307-4707-998b-76a57f0e0766)

**Comment by slinkymanbyday** [comment]
Just wondering, do you have the new console experience or the old one?
Our org was reverted to the old experience, and 1.6 works fine for me. It worked on the new on too for me, but that was a while ago.

**Comment by cjallen88** [comment]
I also have this issue after upgrading to latest - we have the new console experience.

**Comment by viktord** [comment]
The workaround proposed by @lohrm-stabl (replacing "name" with "number") works for me (I see the account name), seems like these variables got messed up.

**Comment by z0ph** [comment]
Same behaviour here. The account name (alias) was the main driver to use this extension.

**Comment by lohrm-stabl** [comment]
This worked a couple of weeks for me, but now it started happening again:
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/111898561/7e318d31-6874-4f8e-874a-8bc3597796d7)
