### ISSUE TITLE
AWS SSO console has been updated and now the container won't open when clicking a link

### ISSUE THREAD

**Issue by JamesNSmith** [pyro2927/AWS_SSO_Containers#19]

**Comment by pyro2927** [comment]
@JamesNSmith have you updated to the latest version of the extension? I received the new AWS dashboard today and everything works since #14 was merged in

**Comment by JamesNSmith** [comment]
Hi
The plugin page was last updated 2 months ago and is on version 1.6:
https://addons.mozilla.org/en-GB/firefox/addon/aws-sso-containers/

**Comment by JamesNSmith** [comment]
It's now on 1.7

**Comment by JamesNSmith** [comment]
It now works again.
Great turn around :)
Thank you
