### ISSUE TITLE
Not working after updating to v1.1

### ISSUE THREAD

**Issue by leytonreed** [pyro2927/AWS_SSO_Containers#2]
This plugin seems to have stopped working for me today following the update to v1.1.

When logging into an AWS account, the initial new tab with the "loading" page comes up, which would usually be closed and replaced with a logged-in session to the AWS Console in a tab container.

Instead, this now sits and loads for a while, before returning an error:
![image](https://user-images.githubusercontent.com/2364685/228193607-a0974426-216a-4b2e-8bfc-8226ceba6df1.png)

Disabling the AWS SSO Containers plugin resolves this, but obviously starts the Console session in a normal tab.

I've tried changing the naming convention in your new settings page, and deleting the existing AWS tab container, but the error persists.

**Comment by leytonreed** [comment]
Removing the add-on from Firefox, deleting the containers, and then reinstalling it seems to have fixed it for me 🤷

**Comment by adds68** [comment]
Also having this issue 111.0.1 (Mac), above solution did not resolve it for me also.

**Comment by JamesNSmith** [comment]
@adds68 Same for me

**Comment by arielm-cloudbuzz** [comment]
+1  Same for me

**Comment by GeertWille** [comment]
+1

**Comment by sebalaterra** [comment]
Same for me. It does not work anymore

**Comment by jakevs-cf** [comment]
+1

**Comment by rcoops** [comment]
+1

**Comment by pyro2927** [comment]
Sorry folks! Thought I had that upgrade flow properly covered. Just pushed v1.2 with the fix.

**Comment by jakevs-cf** [comment]
> Sorry folks! Thought I had that upgrade flow properly covered. Just pushed v1.2 with the fix.

Can confirm it now works. Thanks @pyro2927 !

**Comment by jimsmith** [comment]
I can confirm it also works for me as well - nice one thank you @pyro2927

**Comment by jakevs-cf** [comment]
@pyro2927 

I don't want to raise another issue, but I'm wondering why it is now forcing that naming convention and forcing multiple SSO accounts with the same role name into the same container. No matter how I configure the "Container name template" it names the container "Prod <my-role-name>" (whether it's prod or not). When I try to rename the container, it simple creates a new one following the convention.

I have >30 AWS accounts, each having multiple roles depending on function - All our accounts use the same role names. When I open account**A** role**A** and account**B** also with role**A**, it opens both in the same `Prod roleA` container.

Unfortunately this now makes this extension effectively unusable - and your extension is the only reason I've been sticking with Firefox..

**Comment by pyro2927** [comment]
Hey @jakevs-cf, are you using the default `name role` container naming, or are you trying to do something custom? One issue I'm seeing now is since the extension loads at the browser level and not page level, the container name template is somewhat cached. You can re-load it by disabling then re-enabling the plugin (*not* uninstalling, just toggle it off/on).

The format for pulling account IDs/names/roles is unchanged, so I don't think that would cause an issue.

![image](https://user-images.githubusercontent.com/39943/228299748-e77ec8df-7fc2-45a6-aa32-60aaeddb748d.png)

**Comment by jakevs-cf** [comment]
Thanks, I did what you said and now it manages to keep all my profiles separate, however, I've still lost the ability to rename the containers (if I rename one and reopen the sso account/role again it creates a new containers. This is a minor annoyance so I can probably ;) live with it. Unfortunately the containers extention itself is not very good at handling long strings so the names are all mashed up and that make me itch!
