### ISSUE TITLE
Workaround for an issue with long container names

### ISSUE THREAD

**Issue by acahill** [pyro2927/AWS_SSO_Containers#26]
Hi @pyro2927, thank you so much for this extension, I've been using it for a while now and it makes dealing with frequently switching roles way easier. This isn't a problem with the AWS SSO Containers addon really, but the Firefox Multi-Account Containers addon has a long-standing issue where long container names wrap in a way that makes them jumbled and sometimes illegible:

![container-name-wrapping-fixed](https://github.com/pyro2927/AWS_SSO_Containers/assets/3992307/5ed41450-2079-4b30-b4a0-37dad80884d6)

As far as I can tell, the Mozilla team has ignored the issue [Long Names Word wrap are overlapping with other entries
#2544](https://github.com/mozilla/multi-account-containers/issues/2544), which is probably fair enough given the [usual 25-character limit](https://github.com/mozilla/multi-account-containers/issues/1579). That doesn't apply to this addon, so a while back I patched in a few minor changes to add an option to limit the max length and truncate the name with an ellipsis:

![container-name-dialog-fixed](https://github.com/pyro2927/AWS_SSO_Containers/assets/3992307/1ab4b69d-02ec-45c0-a583-12dd855b30a8)

That turned out to work really well, except if you make the length so short the names end up being identical. Anyway, I put the changes on a fork of the repository https://github.com/acahill/AWS_SSO_Containers, which is now trailing a little bit but still works just fine for me. Is that useful to anyone else? I could rebase it and make a pull request if it helps.

**Comment by pyro2927** [comment]
@acahill if you rebase I'll take the change

**Comment by acahill** [comment]
Brilliant, thanks! I've added a pull request #28

**Comment by pyro2927** [comment]
Closing with merge and v1.10 pushed. Apologies for the delay, life has been busy

**Comment by acahill** [comment]
Hey no worries at all, and thanks for taking a look at it. Apologies in advance if I broke anything, but I've been using the change as a temporary/debugging addon for a while now, and it works well for me. Cheers!
