### ISSUE TITLE
Keeps asking which container to open a new tab in

### ISSUE THREAD

**Issue by 4xgkg** [pyro2927/AWS_SSO_Containers#27]
Hi. This is probably a PEBKAC issue (i.e. user mistake, for those unfamiliar with the term), but I can't find a way to fix this.

Whenever I pick a link to open the AWS console with one of the accounts, I started getting a page like this:
![Screenshot_2024-06-09_at_8_08_42 AM](https://github.com/pyro2927/AWS_SSO_Containers/assets/9516498/f1f17d9b-6d7b-4ddc-82e4-86829dc403fd)

I think this started when I once mistakenly clicked the checkbox.

Before that, clicking on an account link from the list of AWS accounts just opened the portal in that account directly.

I tried clicking on the checkbox again but it doesn't make a difference.

I think that what I need is to somehow clear an internal flag controlled by this checkbox.

How can I get back to the old behaviour which just opened the new account page directly?

This is with extension release 1.9 updated today.

**Comment by anebz** [comment]
In the **Container Tabs** Firefox settings there's this checkmark
![grafik](https://github.com/pyro2927/AWS_SSO_Containers/assets/17035525/ba212693-7658-405f-9ca2-8590d2314174)
maybe you have it enabled?

**Comment by amosshapira** [comment]
> In the **Container Tabs** Firefox settings there's this checkmark ![grafik](https://private-user-images.githubusercontent.com/17035525/341754631-ba212693-7658-405f-9ca2-8590d2314174.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwNDkyNzIsIm5iZiI6MTcxOTA0ODk3MiwicGF0aCI6Ii8xNzAzNTUyNS8zNDE3NTQ2MzEtYmEyMTI2OTMtNzY1OC00MDVmLTljYTItODU5MGQyMzE0MTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIyVDA5MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1MjdhNzdhNjdiNTY0OTIyNzYxMjk3ZDE1YjMwZTA1Yjc4YjdlYzgzNWU0YzRhMjI0MWY1NzFkOTQxY2Y2ZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jLaiFzkqp6lTorLtWdOgkPjFUD-0wnvcleZcH2o1FQ4) maybe you have it enabled?

Thanks for the pointer - it's unchecked for me (appears just like in your sample screenshot)

**Comment by pyro2927** [comment]
@4xgkg does this help? https://github.com/mozilla/multi-account-containers/issues/1730#issuecomment-997712373

**Comment by amosshapira** [comment]
@pyro2927 I ended up uninstalling and re-installing the extension. That made it work nicely again since.
