### ISSUE TITLE
Login is broken following 1.10 

### ISSUE THREAD

**Issue by jmanteau** [pyro2927/AWS_SSO_Containers#30]
This extension is awesome but I have to deactivate it as the signin URL is blocked !
<img width="1214" alt="image" src="https://github.com/user-attachments/assets/129696f0-b9fc-4de0-8abe-822e48a3736d">

**Comment by pyro2927** [comment]
@jmanteau can you provide some more info? What operating system are you on? This is for SAML auth, correct?

**Comment by mrnonz** [comment]
I faced this as well on macOS 14.7

**Comment by jmanteau** [comment]
I'm on MacOS 14.5 and FF 130. This is indeed following the redirection after a SAML auth.

**Comment by pyro2927** [comment]
Should be fixed by v1.11 (2cb47cc7a61590efc61a45a2a3b5a8cce92f3d2d). Please let me know if it doesn't, I don't have a SAML app to test against and want to make sure this flow works for users who need it.

**Comment by mrnonz** [comment]
Yeah, v1.11 fixed the problem. Thanks

**Comment by jmanteau** [comment]
Workin on my side as well. Thank you very much for the quick fix ! This plugin become a little bit more awesome 😻
