### ISSUE TITLE
Cannot Login to IAM SAML since 1.11 Update

### ISSUE THREAD

**Issue by jfevre** [pyro2927/AWS_SSO_Containers#31]
HI Guys love the extension. 
My company have a mix of identity centre and saml idp in I am .
Since the 1.11 update I can no longer login to the SAML in the individual accounts as the extension blocks this.
![image](https://github.com/user-attachments/assets/1fca3fb0-a3d7-43b8-9249-38b17b6afce6)
Is there any sort of fix or workaround for this?

**Comment by pyro2927** [comment]
@jfevre this is after v1.11? Did you restart Firefox after the extension updated? This looks to be the same as #10

**Comment by jfevre** [comment]
Thats just the version i am currently on but its the first time I've experience it.
Im not sure how its related to that issue as  its not just an esthetic. I am unable to login to those saml accounts with this extension enabled I've had to disable it currently.

**Comment by peteawood** [comment]
I have the same problem and it started not long after the update to v1.11. I don't often log into the environment using saml idp so hadn't considered reporting it before now.

**Comment by peteawood** [comment]
After a bit of experimenting, my headers' case do not match the case being searched for. My headers are "Location" and "Set-Cookie" whereas the code is searching for "location" and "set-cookie". Editing the headers prior to the code executing allows the extension to work properly.

Would recommend adding a switch/method call to ignore the case when comparing the header name or updating the string to match the expected case for the header name (although I'm not sure how much you can rely on it being in one case or another, [HTTP/2.0 RFC](https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2) seems to enforce lower case field names)
