### ISSUE TITLE
Have you ported this to Chrome?

### ISSUE THREAD

**Issue by david-macias** [pyro2927/AWS_SSO_Containers#5]
I would love to have this in Chrome too. Is it possible?

**Comment by jpintozzi-rs** [comment]
Last I checked, [Chrome doesn't have support for contextual identities in their browser](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/contextualIdentities#browser_compatibility), so this won't work.

**Comment by david-macias** [comment]
Thanks for your response, closing.
