### ISSUE TITLE
Support Adding a Prefix to Container Names for supporting multiple SSO Portals

### ISSUE THREAD

**Issue by smacintyre** [pyro2927/AWS_SSO_Containers#7]
The workflow for AWS_SSO_Containers breaks down when you have to work with multiple SSO Portals. It would be nice to be able to add a prefix to all the Firefox containers based on which SSO Portal they were opened from. This could be done by reusing the subdomain of the sso portal.

**Comment by pyro2927** [comment]
@smacintyre this and #6 are now resolved as of v1.4, update should be available via Mozilla shortly.

**Comment by smacintyre** [comment]
Thank you very much! ♥️

**Comment by pyro2927** [comment]
You'll want to use `subdomain` in the template name preferences. Thanks for the feedback!
![image](https://github.com/pyro2927/AWS_SSO_Containers/assets/39943/9297429d-1146-44d8-9dd4-4e3dbd0d0581)
