### ISSUE TITLE
Doesnt support non alphanumeric chars to differenciate accounts

### ISSUE THREAD

**Issue by potchin** [pyro2927/AWS_SSO_Containers#8]
My company has a bunch of aws accounts with SSO names like this...

- mycompany (dev)
- mycompany (logs)
- mycompany (prod)

Im guessing the extension is truncating the end off the name (maybe because of non alphanumerics?) and all accounts end up opening in the same container. Obviously this isnt what's intended :)

**Comment by pyro2927** [comment]
@potchin this is specific to the `(` character. The account as referenced in the URI is in the format of `AccountId (AccountName)`. I'd be curious how yours end of looking in the URI, perhaps `AccountId (mycompany (dev))`? I'll have to see if I can construct an account with parenthesis in the name to test against.

**Comment by potchin** [comment]
@pyro2927 Thats exactly how it looks, with 2 sets of brackets. It was a showstopper for me so I ended up moving to [granted.dev](granted.dev) which seems to work.

**Comment by pyro2927** [comment]
[granted.dev](https://www.granted.dev/) is a great tool! I fixed the issue in 1.5 for anyone else who needs it.
