### ISSUE TITLE
Secondary account linked to AWS SSO portal not launching in separate container

### ISSUE THREAD

**Issue by ncs-alexhoward** [pyro2927/AWS_SSO_Containers#9]
Everything works as expected with all accounts and roles controlled by my organization listed under "AWS Account" on my AWS SSO portal page. However, there is another account we do not own or control but have access to in order to manage the environment. It appears as separately in the portal. When I launch this account, it does not launch in its own container. 

Plugin version: 1.3
Firefox version: 116.0.2 (64-bit) - MacOS

**Comment by pyro2927** [comment]
@ncs-alexhoward only thing I can guess is that this is due to the other portal using a different federation URL that the plugin is currently not setup to detect. Do you happen to have any other details on the account that you're willing to share?

**Comment by WTFender** [comment]
@pyro2927 the account he's logging into isn't federated like a typical account in AWS SSO. The account is a generic SAML app (IAM Assume Role) that does hit different federation URLs... [I haven't figured out the differences yet though](https://github.com/WTFender/aws-sso-extender/issues/58#issuecomment-1670486600).

**Comment by pyro2927** [comment]
I appreciate the heads up @WTFender! I'll have to set up an account like that for myself to see what the API responses look like.

**Comment by pyro2927** [comment]
Resolved with #24
